# Generated by Django 4.1.3 on 2022-11-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField(default=0, editable=False)),
                ('name', models.SlugField(max_length=100000)),
                ('symbol', models.SlugField(max_length=5)),
                ('date', models.DateTimeField()),
                ('hight', models.DecimalField(decimal_places=10, max_digits=100)),
                ('low', models.DecimalField(decimal_places=10, max_digits=100)),
                ('open', models.DecimalField(decimal_places=10, max_digits=100)),
                ('close', models.DecimalField(decimal_places=10, max_digits=100)),
                ('volume', models.DecimalField(decimal_places=10, max_digits=100)),
                ('marketcap', models.DecimalField(decimal_places=10, max_digits=100)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'db_table': 'Coins',
            },
        ),
    ]
